// <auto-generated />
using System;
using Domain.Enums;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "t_technician_capability", new[] { "dry_wall", "electrical", "general", "hvac", "machinery", "painting", "plumbing" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "t_user_role", new[] { "manager", "technician", "tenant" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<float>("AreaM2")
                        .HasColumnType("real")
                        .HasColumnName("area_mm2");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bathrooms");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bedrooms");

                    b.Property<decimal>("MonthlyRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_rate");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("property_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("property_id");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<UserRole>("Role")
                        .HasColumnType("t_user_role");

                    b.Property<Guid?>("property_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("property_id");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<UserRole>("Role");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Users.Manager", b =>
                {
                    b.HasBaseType("Domain.Entities.Users.User");

                    b.Property<decimal>("HourlyRate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasIndex("PropertyId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("PropertyId")
                                .HasColumnName("Manager_PropertyId");
                        });

                    b.HasDiscriminator().HasValue(UserRole.Manager);
                });

            modelBuilder.Entity("Domain.Entities.Users.Technician", b =>
                {
                    b.HasBaseType("Domain.Entities.Users.User");

                    b.PrimitiveCollection<string[]>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("HourlyRate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasIndex("PropertyId");

                    b.HasDiscriminator().HasValue(UserRole.Technician);
                });

            modelBuilder.Entity("Domain.Entities.Users.Tenant", b =>
                {
                    b.HasBaseType("Domain.Entities.Users.User");

                    b.Property<DateTime>("MovedIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moved_in");

                    b.Property<DateTime>("MovedOut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moved_out");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(UserRole.Tenant);
                });

            modelBuilder.Entity("Domain.Entities.Property", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("postal_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("state");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("street_name");

                            b1.Property<int>("StreetNumber")
                                .HasColumnType("integer")
                                .HasColumnName("street_number");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Unit", b =>
                {
                    b.HasOne("Domain.Entities.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("property_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Domain.Entities.Property", null)
                        .WithMany("Users")
                        .HasForeignKey("property_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.Users.Manager", b =>
                {
                    b.HasOne("Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Domain.Entities.Users.Technician", b =>
                {
                    b.HasOne("Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Domain.Entities.Users.Tenant", b =>
                {
                    b.HasOne("Domain.Entities.Unit", "Unit")
                        .WithOne("Tenant")
                        .HasForeignKey("Domain.Entities.Users.Tenant", "UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Domain.Entities.Property", b =>
                {
                    b.Navigation("Units");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Unit", b =>
                {
                    b.Navigation("Tenant")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
